//    RUN ACTION SOURCE

#include "RunAction.hh"

RunAction::RunAction(): photonHits(20, 0)
{
 G4AnalysisManager *man = G4AnalysisManager::Instance();


//man->CreateNtuple("Photons","information about the Photons generated by scintillation");
  
   //man->FinishNtuple(0);


  man->CreateNtuple("Edep","Data from each event");
  
  for (G4int i = 0; i < 20; i++) {
        std::stringstream columnName;
        columnName << "Energy_Deposition_MeV_On_Bar_" << i;
        man->CreateNtupleDColumn(columnName.str());
    }


   for (G4int l = 0; l < 20; l++){
      std::stringstream columnName;
      columnName << "Photons_Generated_perEvent_on_Bar_" << l;
      man->CreateNtupleDColumn(columnName.str());
  }


  man->CreateNtupleDColumn("Particle_Momentum_GeV"); // 40 <--
 
  man->CreateNtupleDColumn("Copy_num_Bar_Traversed_A"); // 41
  man->CreateNtupleDColumn("Copy_num_Bar_Traversed_B"); // 42
  man->CreateNtupleIColumn("HIT_particle_passed_both_layers");  // 43 

  man->CreateNtupleDColumn("Total_Energy_Deposition");  // 44

  

man->CreateNtupleSColumn("PARTICLE_NAME_ON_A"); // 45
man->CreateNtupleSColumn("PARTICLE_NAME_ON_B"); // 46

//------------------------------------------------------------------------
  man->CreateNtupleDColumn("total_edep_on_A"); // 47
  man->CreateNtupleDColumn("total_edep_on_B"); // 48


 man->CreateNtupleDColumn("P_t"); //49 <--

  man->CreateNtupleDColumn("Position_x_Detected_On_Layer_A"); // 50
  man->CreateNtupleDColumn("Position_y_Detected_On_Layer_A"); // 51
  man->CreateNtupleDColumn("Position_z_Detected_On_Layer_A"); // 52

  man->CreateNtupleDColumn("Position_x_Detected_On_Layer_B"); // 53
  man->CreateNtupleDColumn("Position_y_Detected_On_Layer_B"); // 54
  man->CreateNtupleDColumn("Position_z_Detected_On_Layer_B"); // 55
  
  man->CreateNtupleDColumn("Total_Photons_Generated");  //56
  man->CreateNtupleDColumn("Total_Generated_Photons_A"); //57
  man->CreateNtupleDColumn("Total_Generated_Photons_B"); // 58

man->CreateNtupleIColumn("fEvent"); //59
  man->FinishNtuple(0);


 
}

RunAction::~RunAction()
{}


void RunAction:: BeginOfRunAction(const G4Run* run)
{
 G4AnalysisManager *man = G4AnalysisManager::Instance(); 

 

 G4int runID = run->GetRunID();

 std::stringstream strRunID;
 strRunID << runID;

 man->OpenFile("Output"+strRunID.str()+".root");


}


void RunAction::EndOfRunAction(const G4Run*)
{
 G4AnalysisManager *man = G4AnalysisManager::Instance();
 
 man->Write();
 man->CloseFile();
}

